apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-app-deployment
  namespace: test
  labels:
    app: feedback-app
spec:
  replicas: 1   # Must be 1 because SQLite cannot run with multi-pod writes
  selector:
    matchLabels:
      app: feedback-app
  template:
    metadata:
      labels:
        app: feedback-app
    spec:
      securityContext: 
        fsGroup: 1000
      containers:
      - name: feedback-app-container
        image: 920971363988.dkr.ecr.us-east-1.amazonaws.com/feedback-app-ecr:v2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

        # MOUNT SQLITE DATABASE DIRECTORY
        volumeMounts:
        - name: sqlite-storage
          mountPath: /app/database

      # PVC FOR SQLITE
      volumes:
      - name: sqlite-storage
        persistentVolumeClaim:
          claimName: sqlite-pvc
