apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-app-deployment
  namespace: test 
  labels:
    app: feedback-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback-app
  template:
    metadata:
      labels:
        app: feedback-app
    spec:
      containers:
      - name: feedback-app-container
        image: 920971363988.dkr.ecr.us-east-1.amazonaws.com/feedback-app-ecr:v2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
