apiVersion: v1
kind: Service
metadata:
  name: feedback-app-service
  namespace: test
spec:
  type: NodePort
  selector:
    app: feedback-app
  ports:
    - protocol: TCP
      port: 80              
      targetPort: 5000 
 
